version: "2"
run:
  go: "1.22"
linters:
  enable:
    - copyloopvar
    - gocyclo
    - gosec
    - misspell
    - revive
    - unconvert
  settings:
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G402
    revive:
      rules:
        - name: exported
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
    paths:
      - examples
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - examples
      - third_party$
      - builtin$
      - examples$
